Bat2_WebApp/BatWebApp/BatApp/Areas/UserAccounts/Models/Company/CompanyViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace BatApp.Areas.UserAccounts.Models.Company
{
   public class CompanyViewModel
   {
      [HiddenInput(DisplayValue = false)]
      public int Id { get; set; }

      [Required]
      public string Name { get; set; }

      [HiddenInput(DisplayValue = false)]
      public string PreviousUrl { get; set; }
   }
}

Bat2_WebApp/BatWebApp/BatApp/Areas/UserAccounts/Models/Company/IndexCompanyViewModel.cs
using PagedList;

namespace BatApp.Areas.UserAccounts.Models.Company
{
   public class IndexViewModel
   {
      public int? UserCompany { get; set; }
      public string Search { get; set; }
      public IPagedList<CompanyViewModel> Companies { get; set; } 
   }
}

Bat2_WebApp/BatWebApp/BatApp/Areas/UserAccounts/Controllers/CompanyController.cs
using System.Linq;
using System.Web.Mvc;
using BatApp.Areas.UserAccounts.Models.Company;
using BatApp.Controllers;
using BatApp.Helpers;
using PagedList;
using DataModel;

namespace BatApp.Areas.UserAccounts.Controllers
{
   [BatApp.Infrastructure.Filters.Authorize(Roles = Constants.ADMIN + ", " + Constants.COMPANY_ADMIN)]
   public class CompanyController : BaseController
   {
      //
      // GET: /Company/
      [Authorize(Roles = Constants.ADMIN)]
      public ViewResult Index(int? page, string search)
      {
         var model = new IndexViewModel();
         var user = CurrentUser;
         model.UserCompany = user.CompanyId;

         var comapanies = Context.Companies.Select(c => new CompanyViewModel {Id = c.Id, Name = c.Name}).ToList();
         if (!string.IsNullOrWhiteSpace(search))
         {
            comapanies =
               Context.Companies.Where(w => w.Name.Contains((search)))
                  .Select(c => new CompanyViewModel {Id = c.Id, Name = c.Name})
                  .ToList();
         }

         model.Search = search;
         model.Companies = new PagedList<CompanyViewModel>(comapanies, page ?? 1, 10);
         return View(model);
      }

      //
      // GET: /Company/Create
      [Authorize(Roles = Constants.ADMIN)]
      public ActionResult Create()
      {
         ViewBag.Create = true;
         return View("Edit", new CompanyViewModel());
      }

      //
      // POST: /Company/Create
      [HttpPost]
      public ActionResult Create(CompanyViewModel companyVm)
      {
         if (!ModelState.IsValid) return View("Edit", companyVm);

         if (Context.Companies.Any(c => c.Name == companyVm.Name))
         {
            ModelState.AddModelError("", Resources.Resources.CompanyExists);
            ViewBag.Create = true;
            return View("Edit",companyVm);
         }

         Context.CreateCompany(companyVm.Name);
         return RedirectToAction("Index");
      }

      public JsonNetResult CheckIfCompanyExists(string name)
      {
         if (Context.Companies.Any(x => x.Name == name))
         {
            return new JsonNetResult
            {
               Data = new
               {
                  error = Resources.Resources.CompanyExists
               }
            };
         }
         return new JsonNetResult
         {
            Data = new
            {
            }
         };
      }

      //
      // GET: /Company/Edit/5
      [Authorize(Roles = Constants.ADMIN + ", " + Constants.COMPANY_ADMIN)]
      public ActionResult Edit(int? id = null)
      {
         if (ViewBag.Create != true)
         {
            ViewBag.Create = false;
         }
         Company company;
         if (id == null)
         {
            var user = CurrentUser;
            if (user != null)
            {
               company = user.Company;
            }
            else
            {
               return HttpNotFound();
            }
         }
         else
         {
            if (User.IsInRole(Constants.ADMIN))
            {
               company = Context.Companies.FirstOrDefault(c => c.Id == id);
            }
            else
            {
               company = null;
            }
            if (company == null)
            {
               return HttpNotFound();
            }
         }

         return View(new CompanyViewModel { Id = company.Id, Name = company.Name, PreviousUrl = HttpContext.Request.UrlReferrer.AbsoluteUri });
      }

      //
      // POST: /Company/Edit
      [HttpPost]
      [Authorize(Roles = Constants.ADMIN + ", " + Constants.COMPANY_ADMIN)]
      public ActionResult Edit(CompanyViewModel companyVm)
      {
         if (!ModelState.IsValid)
         {
            return View(companyVm);
         }
         if (Context.Companies.Any(c => c.Name == companyVm.Name && c.Id != companyVm.Id))
         {
            ModelState.AddModelError("", Resources.Resources.CompanyExists);
            ViewBag.Create = false;
            return View(companyVm);
         }

         var company = Context.Companies.First(c => c.Id == companyVm.Id);
         company.Name = companyVm.Name;
         Context.SaveChanges();
         return User.IsInRole(Constants.ADMIN) 
            ? RedirectToAction("Index")
            : (ActionResult)Redirect(companyVm.PreviousUrl);
      }

      //
      // GET: /Company/Delete/5
      [Authorize(Roles = Constants.ADMIN)]
      public ActionResult Delete(int id = 0)
      {
         var company = Context.Companies.FirstOrDefault(c=> c.Id == id);
         if (company == null)
         {
            return HttpNotFound();
         }
         return View(new CompanyViewModel{Name = company.Name, Id = company.Id});
      }

      //
      // POST: /Company/Delete/5

      [HttpPost, ActionName("Delete")]
      public ActionResult DeleteConfirmed(int id)
      {
         Context.DeleteCompany(id);
         return RedirectToAction("Index");
      }
   }
}

Bat2_WebApp/BatWebApp/BatApp/Areas/UserAccounts/Views/Company/Delete.cshtml
@model BatApp.Areas.UserAccounts.Models.Company.CompanyViewModel
@using BatApp.Helpers
@{
    ViewBag.Title = "BAT2 WEB - Company Delete";
}

<h3>@Resources.Resources.DeleteCompanyWarn @Html.DisplayFor(model => model.Name)?</h3>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" class="submitBtn" value="@Resources.Resources.Delete" />
    </p>
}

<div style="padding-top:15px;">
    @Html.ActionImage("Index", null, "~/Content/images/back.png", "back")
</div>

Bat2_WebApp/BatWebApp/BatApp/Areas/UserAccounts/Views/Company/Edit.cshtml
@model BatApp.Areas.UserAccounts.Models.Company.CompanyViewModel
@using BatApp.Helpers
@{
   ViewBag.Title = "BAT2 WEB - Company Create";
   ViewBag.CurrentPage = "companyPage";
}


@if (ViewBag.Create)
{
   <h2>@Resources.Resources.CreateNewCompany</h2>

   using (Html.BeginForm("Create", "Company", FormMethod.Post, new { @id = "createForm" }))
   {
      @EditName()
   <input type="submit" class="submitBtn" value="@Resources.Resources.CreateBtn" />
   }
}
else
{
   <h2>@Resources.Resources.EditCompany</h2>

   using (Html.BeginForm("Edit", "Company", FormMethod.Post, new { @id = "createForm" }))
   {
      @EditName()
   <input type="submit" class="submitBtn" value="@Resources.Resources.SaveChangesButton" />
   }
}


@if (User.IsInRole(DataModel.Constants.ADMIN))
{
    <div style="padding-top: 15px;">
        @Html.ActionImage("Index", null, "~/Content/images/back.png", "back")
    </div>
}

@helper EditName()
{
   @Html.AntiForgeryToken()
   @Html.ValidationSummary(true, "", new { @class = "alert-danger" })
   @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model =>  model.PreviousUrl)
   <fieldset>
      <legend></legend>
      <div>
         @Html.Label(@Resources.Resources.Company)
      </div>
      <div>
         @Html.EditorFor(model => model.Name)
         @Html.ValidationMessageFor(model => model.Name)
      </div>
   </fieldset>
}

Bat2_WebApp/BatWebApp/BatApp/Areas/UserAccounts/Views/Company/Index.cshtml
@model BatApp.Areas.UserAccounts.Models.Company.IndexViewModel
@using BatApp.Helpers
@using PagedList.Mvc
@using Resources
@{
   ViewBag.Title = Resources.CompanyTitle;
}
@section styles
{
   @Styles.Render("~/Styles/PagedList")
}

<div class="actionbar">
   <a data-toggle="collapse" data-target="#filterBar">
      <img src='@Url.Content("~/Content/images/filter.png")' alt="@Resources.FilterTitle" title="@Resources.FilterTitle"/>
   </a>
</div>

<div id="filterBar" class="collapse">
   <h2 class="userAccounts">
      @Resources.FindCompany
   </h2>
   @using (Html.BeginForm("Index", "Company", FormMethod.Get, new { @class = "userAccounts-searchForm", role = "form" }))
   {
      <fieldset>
         <label for="search">
            @Resources.SearchCompany
         </label>
         <input type="text" name="search" value="@Model.Search" />
         <input type="submit" value="@Resources.Search" class="submitBtn submitUserAdm" />
      </fieldset>
   }
</div>
<h2>
   @if (!string.IsNullOrWhiteSpace(Model.Search))
   {
      <div>(@Html.ActionLink(Resources.ClearSearch, "Index"))</div>
   }
</h2>
<h2 class="userAccounts">@Resources.CompanyTitle (@Html.ActionLink(Resources.NewCompany, "Create"))</h2>

<p/>

<div class="userAccounts-allUsers">
   @if (Model.Companies != null && Model.Companies.Any())
   {
      <ul class="row-fluid userAccounts userAccounts-users">
         @foreach (var company in Model.Companies)
         {
            <li class="row">
               <div class="span2">
                  @{
                     var companies = company.Id;
                  }

                  <div class="userAccounts-username">@Html.ActionLink(company.Name, "Edit", "Company", new {id = company.Id}, null)</div>
               </div>
               @if (Model.UserCompany != company.Id)
               {
                  <div class="span1">
                     @using (Html.BeginForm("Delete", "Company", new {id = company.Id}))
                     {
                        @Html.ActionImage("Delete", new {id = company.Id}, "~/Content/images/delete.png", "delete")
                     }
                  </div>
               }
            </li>
         }
         <li class="row">@Html.PagedListPager(Model.Companies, page => Url.Action("Index", new { page, search = Model.Search }))</li>
      </ul>
     
   }
   else
   {
      <p>@Resources.NoCompanyInfo</p>
   }
</div>