Bat2_WebApp/BatWebApp/BatApp/Controllers/CurvesController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using BatApp.Helpers;
using BatApp.Models;
using DataModel;
using JsAction;

namespace BatApp.Controllers
{
   [BatApp.Infrastructure.Filters.Authorize]
   public class CurvesController : BaseController
   {
      //
      // GET: /Curves/
      [ActionName("StandardGrowthPage")]
      public ActionResult StandardGrowthPage()
      {
         return View();
      }

      /// <summary>
      /// Create new curve with specified name
      /// </summary>
      /// <param name="curveName"></param>
      /// <returns></returns>
      [JsAction(CacheRequest = false)]
      [HttpPost]
      public JsonResult Create(string curveName)
      {
         if (String.IsNullOrEmpty(curveName))
         {
            return new JsonNetResult
            {
               Data = new
               {
                  error = Resources.Resources.ValueCannotBeNullOrEmpty
               }
            };
         }

         if (Context.Curves.Any(x => x.Name == curveName))
         {
            return new JsonNetResult
            {
               Data = new
               {
                  error = Resources.Resources.NameAlreadyExistsError
               }
            };
         }
         var curve = new Curve { Name = curveName, CompanyId = CurrentUser.CompanyId };
         Context.SaveCurve(curve);
         return Json("success");
      }

      /// <summary>
      /// Edit existing curve
      /// </summary>
      /// <param name="curve"></param>
      /// <returns></returns>
      [JsAction(CacheRequest = false)]
      [HttpPost]
      public JsonResult Edit(Curve curve)
      {
         Context.SaveCurve(curve);
         return Json("success");
      }

      [JsAction(CacheRequest = false)]
      [HttpPost]
      public JsonResult DeleteCurves(int[] ids)
      {
         Context.DeleteCurves(ids);
         return Json("Success");
      }

      [JsAction(CacheRequest = false)]
      [HttpGet]
      public JsonResult GetCurves()
      {

         var configCurves = Context.GetConfigCurveIds();
         var result = from c in Context.Curves
                      where !configCurves.Contains(c.Id)
                      orderby c.Name
                      select new { id = c.Id, name = c.Name };

         return new JsonResult { Data = result.ToArray(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
      }

      [JsAction(CacheRequest = false)]
      [HttpGet]
      public JsonResult CurveHandler(JQueryDataTablesRequest param)
      {
         if (Context.Curves == null)
         {
            return new JsonNetResult
            {
               Data = new JQueryDataTablesResponse(param.sEcho, 0, 0),
               JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
         }
         var curve = Context.Curves.FirstOrDefault(c => c.Id == param.curveId);
         if (curve == null)
         {
            return new JsonNetResult
            {
               Data = new JQueryDataTablesResponse(param.sEcho, 0, 0),
               JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
         }

         var curveData = curve.CurveValues.OrderBy(c => c.Day).
            Select(c =>
               new[]
               {
                  Convert.ToString(c.Id),
                  Convert.ToString(c.Day),
                  Convert.ToString(c.Weight, CultureInfo.InvariantCulture)
               }).ToArray();

         return new JsonNetResult
         {
            Data = new JQueryDataTablesResponse(param.sEcho, curveData.Count(), curveData.Count(), curveData),
            JsonRequestBehavior = JsonRequestBehavior.AllowGet
         };
      }

      [JsAction(CacheRequest = false)]
      [HttpPost]
      public int AddData(int? curveId, string weight, int? day)
      {
         if (curveId == null || string.IsNullOrEmpty(weight) || day == null)
         {
            Response.Write("Enter valid values");
            Response.StatusCode = 404;
            Response.End();
            return -1;
         }

         if (Context.Curves.First(x => x.Id == curveId).CurveValues.Any(x => x.Day == day))
         {
            Response.Write("Day'" + day + "' already exists");
            Response.StatusCode = 404;
            Response.End();
            return -1;
         }

         var cv = new CurveValue
         {
            Day = (int)day,
            Weight = Double.Parse(weight.Replace(",", "."), CultureInfo.InvariantCulture)
         };
         Context.Curves.First(x => x.Id == curveId).CurveValues.Add(cv);
         Context.SaveChanges();

         return 1;
      }

      [JsAction(CacheRequest = false)]
      [HttpPost]
      public JsonResult DeleteData(int id)
      {
         Context.DeleteCurvesData(id);
         return Json("Success");
      }

      [HttpPost]
      public string UpdateData(CurveEntryUpdate updateEntry)
      {
         if (updateEntry.Id == 0) return updateEntry.Value;

         var cv = Context.CurveValues.FirstOrDefault(c => c.Id == updateEntry.Id);
         if (cv == null)
         {
            return updateEntry.Value;
         }
         switch (updateEntry.ColumnId)
         {
            case 1:
               cv.Day = int.Parse(updateEntry.Value);
               break;
            case 2:
               {
                  var value = updateEntry.Value.Replace(",", ".");
                  cv.Weight = Double.Parse(value, CultureInfo.InvariantCulture);
               }
               break;
            default:
               return updateEntry.Value;
         }

         Context.SaveChanges();

         return updateEntry.Value;
      }
   }

   public class CurveEntryUpdate
   {
      public int Id { get; set; }
      public string Value { get; set; }
      public int ColumnId { get; set; }
   }
}

Bat2_WebApp/BatWebApp/BatApp/Controllers/FlocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using Bat2Library;
using BatApp.Helpers;
using BatApp.Models;
using DataContext;
using DataModel;
using JsAction;

namespace BatApp.Controllers
{
   /// <summary>
   /// This is controller for flocks
   /// </summary>
   [Infrastructure.Filters.Authorize]
   public class FlocksController : BaseController
   {
      [ActionName("ManagementPage")]
      [Authorize(Roles = Constants.ADMIN + ", " + Constants.COMPANY_ADMIN + ", " + Constants.FLOCK_MANAGEMENT)]
      public ActionResult ManagementPage()
      {
         return View();
      }

      [ActionName("ActualPage")]
      public ActionResult ActualPage()
      {
         return View();
      }

      [ActionName("ClosedPage")]
      public ActionResult ClosedPage()
      {
         return View();
      }

      #region ManagementPage json methods

      /// <summary>
      /// Create new <see cref="Flock"/>
      /// </summary>
      /// <param name="flock">flock to be created</param>
      /// <returns></returns>
      [JsAction(CacheRequest = false)]
      [HttpPost]
      public JsonResult Create(Flock flock)
      {
         if (flock == null || string.IsNullOrEmpty(flock.Name))
         {
            return new JsonNetResult
            {
               Data = new
               {
                  error = Resources.Resources.FlockNameMandatory
               }
            };
         }

         if (!Context.CanCreateFlock(flock))
         {
            return new JsonNetResult
            {
               Data = new
               {
                  error = Resources.Resources.FlockAlreadyExistsError
               }
            };
         }
         if (!String.IsNullOrEmpty(flock.NewScale))
         {
            flock.ScaleId = Context.CreateScale(flock.NewScale);
         }
         Context.SaveFlock(flock);
         return new JsonNetResult
         {
            Data = new
            {
            }
         };
      }

      /// <summary>
      /// Edit existing <see cref="Flock"/>
      /// </summary>
      /// <param name="flock"></param>
      /// <returns></returns>
      [JsAction(CacheRequest = false)]
      [HttpPost]
      public JsonResult Edit(Flock flock)
      {
         if (flock.Name.Equals(string.Empty))
         {
            return new JsonNetResult
            {
               Data = new
               {
                  error = Resources.Resources.FlockNameMandatory
               }
            };
         }
         if (!Context.CanUpdateFlock(flock))
         {
            return new JsonNetResult
            {
               Data = new
               {
                  error = Resources.Resources.FlockAlreadyExistsError
               }
            };
         }

         // if flock can't be created, but can be updated,
         // flock don't have any change and we don't save it
         if (Context.CanCreateFlock(flock))
         {
            Context.SaveFlock(flock);   
         }
         return new JsonNetResult
         {
            Data = new
            {
            }
         };
      }

      /// <summary>
      /// Delete all flocks as specified by their ids
      /// </summary>
      /// <param name="ids">ids of flocks to delete</param>
      /// <returns></returns>
      [JsAction(CacheRequest = false)]
      [HttpPost]
      public JsonResult DeleteFlocks(int[] ids)
      {
         Context.DeleteFlocks(ids);
         return Json("Success");
      }

      /// <summary>
      /// Close flocks, aka set closing date to specific date.
      /// </summary>
      /// <param name="ids">ids of flocks to close</param>
      /// <param name="closedDate">closed date of flocks</param>
      /// <returns>status result</returns>
      [JsAction(CacheRequest = false)]
      [HttpPost]
      public JsonResult CloseFlocks(int[] ids, DateTime closedDate)
      {
         Context.CloseFlocks(ids, closedDate);
         return Json("Success");
      }

      /// <summary>
      /// Close flocks, aka set closing date to null value.
      /// </summary>
      /// <param name="ids">ids of flocks to reopen</param>
      /// <returns>status result</returns>
      [JsAction(CacheRequest = false)]
      [HttpPost]
      public JsonResult ReopenFlocks(int[] ids)
      {
         Context.ReopenFlocks(ids);
         return Json("Success");
      }

      /// <summary>
      /// Get all existing flocks, opened and closed.
      /// </summary>
      /// <returns>Flock object with name and id properties.</returns>
      [JsAction(CacheRequest = false)]
      [HttpGet]
      public JsonResult GetAllFlocks()
      {
         var flocks = Context.Flocks.Select(x => new { name = x.Name, id = x.Id }).OrderBy(x => x.name);
         return new JsonNetResult { Data = flocks.ToArray(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
      }

      /// <summary>
      /// Gets all opened flocks.
      /// </summary>
      /// <returns>Flock object with name and id properties.</returns>
      [JsAction(CacheRequest = false)]
      [HttpGet]
      public JsonResult GetOpenedFlocks()
      {
         var flocks = Context.GetOpenFlocks().Select(x => new { name = x.Name, id = x.Id }).OrderBy(x => x.name);
         return new JsonNetResult { Data = flocks.ToArray(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
      }

      /// <summary>
      /// Gets flocks names by their ids.
      /// </summary>
      /// <param name="ids">ids of flocks to get names for</param>
      /// <returns>Flock names - objects with name property</returns>
      [JsAction(CacheRequest = false)]
      [HttpGet]
      public JsonResult GetFlockNameById(int[] ids)
      {
         var selectedFlocks = CurrentUser.SelectedFlocks.Select(x => x.Id);
         var flocks = Context.Flocks.Where(x => ids.Contains(x.Id)).OrderBy(x => x.Name).Select(x => new { name = x.Name, selected = selectedFlocks.Contains(x.Id) });
         return new JsonNetResult { Data = flocks.ToArray(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
      }

      /// <summary>
      /// Get single flock as specified by id.
      /// </summary>
      /// <param name="id">id of flock to be loaded.</param>
      /// <returns><see cref="Flock"/> object which fully describes a single flock</returns>
      [JsAction(CacheRequest = false)]
      [HttpGet]
      public JsonResult GetFlock(int id)
      {
         return new JsonNetResult { Data = Context.GetFlock(id), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
      }

      #endregion

      [JsAction(CacheRequest = false)]
      [HttpGet]
      public JsonResult GetScales()
      {
         var scales = Context.Scales.OrderBy(x => x.Name).ToArray();
         return new JsonNetResult { Data = scales, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
      }

      [JsAction(CacheRequest = false)]
      [HttpGet]
      public JsonResult GetCurves()
      {
         var curves = Context.Curves.ToArray();
         return new JsonNetResult { Data = curves, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
      }

      [JsAction(CacheRequest = false)]
      [HttpGet]
      public JsonResult StatisticsHandler(JQueryDataTablesRequest param, int? growthCurveId)
      {
         int totalRecords;

         if (HttpContext.Request.QueryString["selectedFlocks"].Length > 0)
         {
            try
            {
               var data = HttpContext.Request.QueryString["selectedFlocks"].Split(',');
               param.selectedFlocks = data.Select(n => Convert.ToInt32(n)).ToArray();
            }
            catch (Exception e) { }
         }
         var stats = Context.GetStats(param.ToFilterModel(), ParseRequest(), out totalRecords, selectedCurveId: growthCurveId);

         return new JsonNetResult
         {
            Data = new JQueryDataTablesResponse(param.sEcho, totalRecords, totalRecords, stats),
            JsonRequestBehavior = JsonRequestBehavior.AllowGet
         };
      }

      private double GetStat(Stat stat, PropertyInfo prop)
      {
         return (double)prop.GetValue(stat, null);
      }

      [JsAction(CacheRequest = false)]
      [HttpGet]
      public JsonResult GetGraphData(int[] flockIds, int? flockId, string graphType, string graphType2, string sex, DateTime? from, DateTime? to)
      {
         if (flockIds == null)
         {
            return new JsonNetResult
            {
               Data = null,
               JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
         }

         var selected = CurrentUser.SelectedFlocks.Select(sc => sc.Id).ToList();
         if (flockId != null)
         {
            flockIds = new[] { (int)flockId };
            selected.Clear();
            selected.Add((int)flockId);
         }

         int xMaxValue = int.MinValue;
         int xMinValue = int.MaxValue;

         double yMinValue = double.MaxValue;
         double yMaxValue = double.MinValue;

         double yMinValue2 = double.MaxValue;
         double yMaxValue2 = double.MinValue;

         if (graphType == null)
         {
            graphType = "Average";
         }
         var stat = typeof(Stat).GetProperty(graphType);
         var xNameValue = Resources.Resources.Days;
         var yNameValue = Resources.Resources.ResourceManager.GetString(graphType + "MenuItem");

         PropertyInfo stat2 = null;
         var yNameValue2 = "";
         if (!string.IsNullOrEmpty(graphType2))
         {
            stat2 = typeof(Stat).GetProperty(graphType2);
            yNameValue2 = Resources.Resources.ResourceManager.GetString(graphType2 + "MenuItem");
         }

         var rawList = Context.Flocks.Where(f => flockIds.Contains(f.Id)).ToList();
         var sexE = SexE.SEX_UNDEFINED;
         if (sex != null)
         {
            sexE = sex == Resources.Resources.SexMale
               ? SexE.SEX_MALE

Bat2_WebApp/BatWebApp/BatApp/Views/Shared/GetAvailableCompanies.cshtml
@model BatApp.Models.CompanyVm
@{
   Layout = null;
}

@Html.DropDownListFor(x => x.Company, Model.Companies, "Select Company")

Bat2_WebApp/BatWebApp/BatApp/Views/Shared/_AccountPartial.cshtml
@using Resources
@if (Request.IsAuthenticated)
{
   using (Html.BeginForm("LogOff", "Account", new { area = "UserAccounts" }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
   {
      @Html.AntiForgeryToken()
      <ul style="list-style: none; margin-left: 0">
         <li>@Html.ActionLink(Resources.AccountSettings, "Index", "Account", new { area = "UserAccounts" }, null)</li>
         <li><a href="javascript:document.getElementById('logoutForm').submit()">@Resources.LogOff</a></li>
      </ul>
   }
}
else
{
   <ul style="list-style: none; margin-left: 0">
      <li>@Html.ActionLink(Resources.LogIn, "Login", "Account", new { area = "UserAccounts" }, htmlAttributes: new { id = "loginLink" })</li>
   </ul>
}

Bat2_WebApp/BatWebApp/BatApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8"/>
   <title>@ViewBag.Title</title>
   <meta name="viewport" content="width=device-width"/>
   <meta http-equiv="X-UA-Compatible" content="IE=9">
   @Styles.Render("~/Content/common")
   @RenderSection("styles", required: false)
</head>
<body>
<div class="container-fluid">
      <div class="row-fluid">
         <div class="span2">
            <div class="navbar">
               <div class="navbar-inner">
                  <div class="container">
                     
                     <a class="brand" href="#"></a>
                     @if (@User.Identity.IsAuthenticated)
                     {
                        <a class="btn btn-navbar menu" data-toggle="collapse" data-target=".nav-collapse">
                           <img src="@Url.Content("~/Content/images/menu.png")" alt="menu" height="30" />
                        </a>
                        <div class="nav-collapse collapse">
                           <ul class="nav nav-list">
                              <li class="nav-header">@Resources.Resources.StatisticsTitle</li>
                              <li>
                                 <a href="@Url.Action("WeighingsPage", "Weighings", new {area = ""})" title=@Resources.Resources.CollectedDataTitle>@Resources.Resources.CollectedDataTitle</a>
                              </li>
                              <li class="nav-header">@Resources.Resources.FlocksTitle</li>
                              @if (User.IsInRole(DataModel.Constants.ADMIN) || User.IsInRole(DataModel.Constants.COMPANY_ADMIN) || User.IsInRole(DataModel.Constants.FLOCK_MANAGEMENT))
                              {
                                 <li>
                                    <a href="@Url.Action("ManagementPage", "Flocks", new {area = ""})" title=@Resources.Resources.ManagementTitle>@Resources.Resources.ManagementTitle</a>
                                 </li>
                              }
                              <li>
                                 <a href="@Url.Action("ActualPage", "Flocks", new {area = ""})" title=@Resources.Resources.ActualFlocksTitle>@Resources.Resources.ActualFlocksTitle</a>
                              </li>
                              <li>
                                 <a href="@Url.Action("ClosedPage", "Flocks", new {area = ""})" title=@Resources.Resources.ClosedNavigation>@Resources.Resources.ClosedNavigation</a>
                              </li>
                              <li class="nav-header">@Resources.Resources.ScalesTitle</li>
                              <li>
                                 <a href="@Url.Action("Index", "Scales", new {area = ""})" title=@Resources.Resources.ScalesLink>@Resources.Resources.ScalesLink</a>
                              </li>
                              <li class="nav-header">@Resources.Resources.CurvesTitle</li>
                              <li>
                                 <a href="@Url.Action("StandardGrowthPage", "Curves", new {area = ""})" title=@Resources.Resources.StandardGrowthTitle>@Resources.Resources.StandardGrowthTitle</a>
                              </li>
                              @if (User.IsInRole(DataModel.Constants.ADMIN) || User.IsInRole(DataModel.Constants.COMPANY_ADMIN))
                              {
                                 <li class="nav-header">@Resources.Resources.SettingsTitle</li>          
                                 <li><a href="@Url.Action("Index", "Manage", new {area = "UserAccounts"})" title=@Resources.Resources.UsersTitle>@Resources.Resources.UsersTitle</a></li>
                              }
                              @if (User.IsInRole(DataModel.Constants.ADMIN))
                              {
                                 <li><a href="@Url.Action("Index", "Company", new {area = "UserAccounts"})" title=@Resources.Resources.CompaniesPageTitle>@Resources.Resources.CompaniesPageTitle</a></li>
                              }
                              else if (User.IsInRole(DataModel.Constants.COMPANY_ADMIN))
                              {
                                 <li><a href="@Url.Action("Edit", "Company", new {area = "UserAccounts"})" title=@Resources.Resources.CompanyPageTitle>@Resources.Resources.CompanyPageTitle</a></li>
                              }

                              <li class="divider"></li>

                           </ul>
                        </div>
                     }
                  </div>
               </div>
            </div>
            <!--/.well -->
         </div>
         <!--/span-->
         <div class="span10">
            <div class="pull-right">
               <div class="dropdown pull-right" style="float: right; margin: 5px 5px;">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                     <i class="icon-globe"></i><span id="curentLang"></span>
                     <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu lang-picker">
                     @foreach (var culture in BatApp.Helpers.CultureHelper.GetAvailableCultures())
                     {
                        <li><a href="javascript:void(0);" class="@culture">@culture</a></li>
                     }
                  </ul>
               </div>
               @if (@User.Identity.IsAuthenticated)
               {
                  <div class="dropdown pull-right" style="float: right; margin: 5px 5px;">
                     <a class=" dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="icon-user"></i>@User.Identity.Name
                        <span class="caret"></span>
                     </a>
                     <ul class="dropdown-menu">
                        <li>@Html.Partial("_AccountPartial")</li>
                     </ul>
                  </div>
               }
            </div>
            <div class="hero-unit">
               @RenderBody()
            </div>
         </div>
         <!--/span-->
      </div>
      <!--/row-->

      @*<footer>
         <hr>
         <p>
            <a href="http://www.veit.cz" target="_blank">
               <img src="@Url.Content("~/Content/images/veitlogo.png")" alt="Veit" title="Veit electronics">
            </a>&copy;@DateTime.Now.Year
         </p>
      </footer>*@
   </div>
   <!--/.fluid-container-->
   <!-- Javascript
      ================================================== -->
   @Scripts.Render("~/Scripts/common")
   @RenderSection("scripts", required: false)
<script>
   var baseURL = '@Url.Content("~/")';
   $(document).ready(function () {
      if (detectIE()) {
         if ($('.modal').hasClass('fade')) {
            $('.modal').addClass('hide');
         }
         $('.modal').removeClass('fade');
      }
      $.datepicker.setDefaults($.datepicker.regional[$.cookie("_culture")]);
   });

   function detectIE() {
      var ua = window.navigator.userAgent;

      var msie = ua.indexOf('MSIE ');
      if (msie > 0) {
         // IE 10 or older => return version number
         return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
      }

      var trident = ua.indexOf('Trident/');
      if (trident > 0) {
         // IE 11 => return version number
         var rv = ua.indexOf('rv:');
         return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
      }

      var edge = ua.indexOf('Edge/');
      if (edge > 0) {
         // IE 12 => return version number
         return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
      }

      // other browser
      return false;
   }

   $(function () {

      $("#curentLang").append(function () {
         @*if ($.cookie("_culture") == undefined) {
                         $.cookie("_culture", "@(BatApp.Helpers.CultureHelper.GetBrowserCulture())", { expires: 365, path: '/' });
                     }*@
         return $.cookie("_culture");
      });

      $(".lang-picker a").click(function () {
         if ($(this).hasClass(Globalize.culture().name.toLowerCase()))
            return false; // do nothing
         $.cookie("_culture", $(this).attr("class"), { expires: 365, path: '/' });
         window.location.reload(); // reload
         return true;
      });

      $(".validationMessage").tooltip();
   });
</script>
</body>
</html>